[workspace]
members = [
    "crates/openjill-data",
    "crates/openjill-core",
    "crates/openjill-game",
    "crates/openjill-render",
    "crates/openjill-ui",
    "crates/openjill-audio",
    "crates/openjill-cli",
    "tools/openjill-dump",
    "tools/openjill-ui-demo",
    "tools/openjill-sha-extract",
    "tools/openjill-sha-edit",
    "tools/openjill-jn-extract",
    "tools/openjill-jn-view",
    "tools/openjill-dma-extract",
    "tools/openjill-vcl-extract",
    "tools/openjill-cfg-extract",
    "tools/openjill-cfg-view",
    "crates/openjill-export",
]
resolver = "3"

[workspace.package]
authors = ["OpenJill contributors"]
edition = "2024"
license = "MPL-2.0"
rust-version = "1.95"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1.0.102"
assert2 = "0.4.0"
bytemuck = { version = "1.25.0", features = ["derive"] }
clap = { version = "4.6.1", features = ["derive"] }
eframe = { version = "0.34.2", default-features = false, features = ["wgpu", "x11", "wayland"] }
egui = "0.34.2"
egui-wgpu = "0.34.2"
image = { version = "0.25.10", default-features = false }
pollster = "0.4.0"
png = "0.18.1"
serde_json = "1.0.150"
sha2 = "0.11.0"
thiserror = "2.0.18"
wgpu = "29.0.3"
winit = "0.30.13"
