[package]
name = "openjill-ui-demo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "openjill-ui-demo"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
eframe.workspace = true
egui.workspace = true
openjill-ui = { path = "../../crates/openjill-ui" }
