[package]
name = "openjill-dma-extract"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "openjill-dma-extract"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
openjill-data = { path = "../../crates/openjill-data" }
openjill-export = { path = "../../crates/openjill-export" }
serde_json.workspace = true

[dev-dependencies]
assert2.workspace = true
